### ISSUE TITLE
Lexer: AutoHotkey.lcf missing

### ISSUE THREAD

**Issue by hi5** [Alexey-T/CudaLister#1]
`AutoHotkey.cuda-lexmap` is present but `AutoHotkey.lcf` is missing so it doesn't highlight AutoHotkey files out of the box. After manually adding `AutoHotkey.lcf` highlighting works correctly.

Same might be true for **Lola-2** (missing LCF)

**Comment by Alexey-T** [comment]
deleted Lola-2 file.
added AHK lexer. Thanks for report
