### ISSUE TITLE
Highlight all matches when double-clicking a word

### ISSUE THREAD

**Issue by Jacques10967** [Alexey-T/CudaLister#100]
Would it be possible to highlight all matches of a double-clicked word in the text

That's what I am getting in lister when double-clicking "taskbar"

![image](https://user-images.githubusercontent.com/18515149/214416518-f481e321-94be-4047-9fc2-867bb186b0af.png)

And that's what I would like to get (notepad++)
![image](https://user-images.githubusercontent.com/18515149/214417303-097b8c34-ba92-4243-841b-f9e34ef181ca.png)

**Comment by Alexey-T** [comment]
this featrture exists. but not in cudalister. it exists in cudatext.
separate editor in my github.
