### ISSUE TITLE
Перестал работать F3 в последнем обновлении

### ISSUE THREAD

**Issue by gtumanyan** [Alexey-T/CudaLister#103]
Для открытия диалогa поиска теперь приходится использовать Ctrl+f

**Comment by springsunx** [comment]
- Ctrl+F - call 'find' dialog
- F3 - find next
- Shift+F3 - find previous

**Comment by gtumanyan** [comment]
In original lister F3 = Ctrl+F
It opens 'find' dialog and then searches next
