### ISSUE TITLE
Add in next versions

### ISSUE THREAD

**Issue by EvgenyM2** [Alexey-T/CudaLister#110]
Author please add the [CudaListerDark] section to the settings. So that you can automatically pick up the theme settings when changing the night style. And it would be nice to set shortcut CTRL+F to search (standard for all editors). Thank you.

**Comment by Alexey-T** [comment]
Maybe you can make the patch? I don’t know what is dark mode.

**Comment by EvgenyM2** [comment]
This is for the Total Commander plugin. There is a night style... when you switch to it, the settings are taken from sections like [Lister] [ListerDark]. the plugin also has a [CudaLister] section, but I would also like to have the settings taken from [CudaListerDark] when switching to night style. Or do you have nothing to do with the plugin?

**Comment by Alexey-T** [comment]
how my plugin can detect that TC is in the dark mode ? I don’t know. If it cannot , when plugin must use the Dark section?

**Comment by EvgenyM2** [comment]
Alexey-T i dont know how. In TC, functions are responsible for this: 

cm_SwitchDarkmode=2950;Turn dark mode on and off
cm_EnableDarkmode=2951;Turn dark mode on
cm_DisableDarkmode=2952;Turn dark mode off

It might work out somehow in the future.

**Comment by Alexey-T** [comment]
I don’t know how to solve it then

**Comment by Alexey-T** [comment]
cannot solve it then,
