### ISSUE TITLE
Does not recognize Russian letters

### ISSUE THREAD

**Issue by OmlineEditor** [Alexey-T/CudaLister#111]
Открываю вашим листером .log файлы в них подсвечиваются только слова с английскими словами: **error|exception|fail|fatal**

Но у меня в логих вывод по русски и там есть слова "**Ошибка**", я пытаюссь добавить эти слова в файл: Logfiles.lcf
Вот так выглядит строка, я туда только слова **|Ошибка|ошибка** добавила:
```
item
      DisplayName = 'Error'
      StyleName = 'Error'
      TokenType = 4
      Expression = 
        '^.*(error|Ошибка|ошибка|exception|fail|fatal|crash|(?<!be)fehl(geschlagen)?(er' +
        ')?|(ohne|kein|nicht)\serfolg|violat).*$'
      ColumnFrom = 0
      ColumnTo = 0
    end
```
Ничего не работает эти слова не подсвечиваются. Я использовала кодировку UTF-8 и windows символы окончания строк.

Можете добавить поддержку ключевых слов на русском?
- - - -
wlx cudalister 1.8.1.0
Total commander 10.50

**Comment by Alexey-T** [comment]
Надо добавлять ру слова не ручной правкой а через диалог правки лексера. В редакторе Synwrite. Кажется движку нужна кодировка не utf8.
