### ISSUE TITLE
Problem with the coloring of the scrollbar

### ISSUE THREAD

**Issue by OmlineEditor** [Alexey-T/CudaLister#114]
В новой версии листера полосы прокрутки стали просто вырвиглазные, они другого цвета и сильно отвтекают от самого окна.
Можно их вернуть в обычный цвет как было раньше в серый цвет как и любые другие элементы в системе.

Windows 7 x64
TC 10.50
cudalister 1.8.1

![color](https://github.com/Alexey-T/CudaLister/assets/13348933/a57afe4d-b87b-4880-994d-cd02924efc9f)

**Comment by Alexey-T** [comment]
в меню правого клика, выберите Config (или Options, я счас не под виндой). и там в диалоге опций выберите "тему". поможет?

**Comment by OmlineEditor** [comment]
Слава богу помогло, глаза вернулись в норму. там есть переменная я ее поменяла на 
`"ScrollFill" : "#D1D1D4",`

Вопрос: Зачем нужно было даже полосу прокрутки менять? Это же даже не тема, а окно самой Windows. Можете ответить и закрывать тему. Спасибо за подсказку.

**Comment by OmlineEditor** [comment]
еще вопрос, скажите какой параметр отвечает за цвет фона вот той обласки на мини карте? Методом научного тыка я не смогла найти, поменяла все что можно чтобы найти, а оно не находится :-(

![color](https://github.com/Alexey-T/CudaLister/assets/13348933/a9003cce-9e9c-444a-a223-6e65937681bc)

**Comment by Alexey-T** [comment]
не могу сказать "зачем нужно было менять полосу". не менял специально. случайно так. может темизация полосы отвалилась? когда зайду в винду (неделя - 2) то посмотрю.

**Comment by Alexey-T** [comment]
>еще вопрос, скажите какой параметр отвечает за цвет фона вот той обласки на мини карте? 
 
видимо это "фон текста" и оно же и фон миникаррты.
проверка в cudatext:
![Screenshot_2023-07-03_14-37-53](https://github.com/Alexey-T/CudaLister/assets/4154978/cfcea62e-fda5-49fb-a178-e5be147f0728)

**Comment by OmlineEditor** [comment]
нет, мне не цвет всего фона нужно, а только цвет под прямоугольником в мини карте в том месте где сейчас идет просмотр, на картинке я показала его стрелкой. Кстати заметила что в Листере для TC этот цвет всегда выделен, а в самой программе cudatext это место подсвечивается только когда я туда курсор навожу и начинаю таскать за это место по мини карте.
Если этого цвета вообще нигде нет то прошу его добавить и сделать всегда видимым, а не только когда курсор навожу, в syblime text этот прямоугольник всегда выдимый и его цвет можно настраивать, пример ниже на картинке.

![compare](https://github.com/Alexey-T/CudaLister/assets/13348933/e7b7dd0e-6f49-4b28-bb80-0e1b7abf93c0)

**Comment by Alexey-T** [comment]
в cudatext видимость этого слайдера - по опции.

![Screenshot_2023-07-03_22-32-29](https://github.com/Alexey-T/CudaLister/assets/4154978/b60d0446-0239-466b-9c1c-50d598bcb465)

потом включу его всегда в листер-плагине.

**Comment by Alexey-T** [comment]
цвет слайдера менять можно.
в файлах *.cuda-theme-ui :

`  "EdMinimapSelBg" : "#FFC993",`

**Comment by OmlineEditor** [comment]
> в cudatext видимость этого слайдера - по опции.

Господи чего все такое не дружелюбное, я даже с трудом смогля понять как включить меню как у вас на картинке, кругом одни текстовые конфики в которых с трудом разбираюсь, но всеже разбираюсь, я еще не полная блондинка.
Поменяла и мето теперь подсвечивается всегда, спасибо.



> цвет слайдера менять можно. в файлах *.cuda-theme-ui :
> ` "EdMinimapSelBg" : "#FFC993",`

Поменяла значение, на на экране ничего не изменилось, цвет прямоуголника на мини карте такой же как и был. Это что-то не то.

**Comment by Alexey-T** [comment]
по коду вижу что этот "цвет" нигде не применяется. странно. буду искать.

"недружелюбно" - по 1вых похоже на Сублиме. так что многие сразу найдут как менять опции. во 2х, есть этот раздел вики - 


[5 Configs](https://wiki.freepascal.org/CudaText#Configs)
    [5.1 File types config](https://wiki.freepascal.org/CudaText#File_types_config)

плагин OptionsEditorLite не имеет хелпа, но там кажется все и так понятно.

**Comment by OmlineEditor** [comment]
Что если пользователь захочет другой оттенок, а у вас там только темней и светлей?
Можно вернуть как было?

**Comment by Alexey-T** [comment]
нет, цвет слайдера миникарты поменять нельзя. сорри.

я под Линуск под wine поставил TC x64, в нем установил плагин. запустил. цвета скроллбаров не такие как вы показали в начале темы. а просто серые светлые. повтора нет.

**Comment by OmlineEditor** [comment]
цвета скроллбаров, это вы имели введу цвета полосы прокрутки?
Я поменяла тему и там поменялись цвета полосы прокрутки, так что самый первый вопрос закрыт.
Остался только второй вопрос про цвета прямоугольника на мини карте где сейчас идет просмотр. Вы сказали этот цвет нельзя менять. Ну тогда у нас все проблемы решены, Точне первая проблема решена, а вторую нельзя решить.
Тикет можно закрывать.
