### ISSUE TITLE
CudaLister is not working with files that have non-printable ASCII char

### ISSUE THREAD

**Issue by anzo42** [Alexey-T/CudaLister#120]
Hi, I found a case where CudaLister does not start when a file contains a non-printable ascii character, but file it self is not binary.

![CudaLister](https://github.com/Alexey-T/CudaLister/assets/31290050/d8b9350b-d0d0-4522-ae55-ba92c5b2e958)

Is it possible to force such files to be opened as normal and have all the extras such as lexer etc.

[Test.log](https://github.com/Alexey-T/CudaLister/files/14241670/Test.log)
[Test2.log](https://github.com/Alexey-T/CudaLister/files/14241671/Test2.log)

**Comment by Alexey-T** [comment]
get the src code.
it has file file_proc.pas.
find this

```

function IsAsciiControlChar(n: integer): boolean; inline;
const
  cAllowedControlChars: set of byte = [
    7, //Bell
    8, //Backspace
    9, //Tab
    10, //LF
    13, //CR
    12, //FormFeed
    26, //EOF
    27 //Escape
    ];
begin
  Result:= (n < 32) and not (byte(n) in cAllowedControlChars);
end; 
```
find what char code breaks the loading,
add this code to 
```
function IsAsciiControlChar(n: integer): boolean; inline;     
```

if you can compile, of coz.

**Comment by Alexey-T** [comment]
or tell me what char code is 'bad'.
maybe i can add this char code to cudalister src.

**Comment by anzo42** [comment]
Thanks for your anwser.
Sorry for the late reply, when I received the notification that you replied, I tried to build the plugin myself, but I had a problem when I tried to add the ATSynEdit package to Lazarus, it complained that it could not compile because the CanvasInvertRectEmptyInside() identifier was not found, although I had already installed ATFlatControls. 
I've never used Lazarus before, so I was a little discouraged, but I finally figured it out and added some characters that I noticed as strange artifacts in the log4net logs, but I still need to look into it a bit more because not every log is running in CudaLister yet.

Anyway, thanks again, once I collect the full list of control chars that were problematic, I'll share them so you can decide if you want to add them to the exceptions.

**Comment by anzo42** [comment]
Hi, it looks like the problematic characters are 2, 5 and 6. I added them to the list you mentioned and so far all the log4net logs I had a problem with are opening correctly.

**Comment by Alexey-T** [comment]
I cannot add chars 2, 5, 6 to the ignore list: it is chars for binary-only files.
