### ISSUE TITLE
Large files do not use Cuda - and selecting it from the lister plugin menu has no effect.

### ISSUE THREAD

**Issue by eyevish** [Alexey-T/CudaLister#129]
Some background on why I installed CudaLister : I was hunting for a plugin is to see line # features of files in the lister - even a summary of line #  could have sufficed. Thanks for the plugin though.

Post installation I found that the regular lister would show some files and other worked fine for CudaLister, turned out that it was a problem with large files (I was trying to look for CSV line counts/numbers). the file that I tested with was about 70 MB.

Is this a intentional limitation to the plugin to avoid lexer overhead on large files ?

**Comment by Alexey-T** [comment]
code shows this line

```
    OptMaxFileSizeMb:= ReadInteger(ListerIniSection, 'max_size', OptMaxFileSizeMb);
```

where default is 2 (Mb). try to change the option 'max_size' in the [CudaLister] section of default plugin config file (file which TCmd passes to plugin via API call).

**Comment by Alexey-T** [comment]
also this option is officially visible in the Options dialog of plugin.
