### ISSUE TITLE
Can't open a specific file type

### ISSUE THREAD

**Issue by JBerry910** [Alexey-T/CudaLister#130]
I can open any "text" based file except one file type.  They are all small files ranging in size from 70k - 92k and are entirely text.  It displays properly when opened in CudaText and other Lister plugins that support text viewing.  Originally I thought it was the extension, which is .ui; however, I have renamed some to .txt and they still do not open in CudaLister.  

I can still open them in CudaText, so this is not a huge issue, but I would love to understand why.  Does CudaLister read the file and reject it based upon content?  I have attached one of the files if you care to examine it.  They are configuration files for an editor that I have had since the 90's and use occasionally even today.  

Not related, but I need to tell you how much I like CudaText.  Its ability to work with data that needs to be revised into columns is the best I have ever used.  The options for multiple carets and alignment make it easy to use. Thank you!

Joe Berry
[Current_jdb_win.txt](https://github.com/user-attachments/files/17284965/Current_jdb_win.txt)

**Comment by Alexey-T** [comment]
I added CudaText console msg about found binary chars.
and i see that it shows 'char 0x10' for this sample file.
it means char code 16 which is not allowed. CudaText shows warning, CudaLister silently fails.

**Comment by Alexey-T** [comment]
thanks for kind words!

**Comment by Alexey-T** [comment]
this is char 0x10 found by Find dialog

![Screenshot from 2024-10-08 06-04-36](https://github.com/user-attachments/assets/4605cc78-1a51-4672-bdde-860a39080f37)

**Comment by JBerry910** [comment]
Thank you  for your prompt reply!

________________________________
