### ISSUE TITLE
Could CudaLister Configure the Default Codepage

### ISSUE THREAD

**Issue by thomasmolover** [Alexey-T/CudaLister#18]
The plugins can select the codepage include CJK in statusbar , but sometime, it could not select the right copage when quickview somefile, then it can't show right. special to local copage file like CHS.
so I suggest it can add a setup file to select a default codepage etc. when the plugins can not  recognize the file format.

**Comment by Alexey-T** [comment]
It's not needed for most users, I can add this opt for donation $30
