### ISSUE TITLE
Options dialog, text is cut-off 

### ISSUE THREAD

**Issue by Horst12** [Alexey-T/CudaLister#28]
In the option dialog there are some texts are cut off.
The line number and tabs size lines are only displayed with their upper half.
See the attached screen shot.
![screenshot - 21 04 2018 15_58_17](https://user-images.githubusercontent.com/38587340/39085236-15a8d0e4-4580-11e8-8977-3de139ae5a99.png)

**Comment by Alexey-T** [comment]
Thanks, fixed, will update ASAP
