### ISSUE TITLE
Bad highlight color on dark background

### ISSUE THREAD

**Issue by qijianjun** [Alexey-T/CudaLister#31]
The default color shceme is wonderfull, but if I change the backgroud to a dark color, #272822 for example, the highlight color perform badly for the unshowy contrast.
Someone will prefer a dark theme for some reason, so if there is option to change the highlight scheme or an instruction to customize it, it will be great.

**Comment by Alexey-T** [comment]
Next ver will have option for ui themes, wait for it.
