### ISSUE TITLE
CudaLister 1.5.5 on DC64 0.8.4 64bits crashes

### ISSUE THREAD

**Issue by dmicsa** [Alexey-T/CudaLister#35]
I try CudaLister 1.5.5 in TC64 and DC64 0.8.4 64bits. In TC works OK in DC crashes after 10 seconds of usage or trying to set something in the plugin.

Looks like the problem is at this line (as per Skif_off digging):

FTotalCmdWindow  := FindWindow('TTOTAL_CMD', nil);

https://github.com/Alexey-T/CudaLister/blob/master/form_main.pas#L609

Can be something done simply to support this wonderful plugin on Dual Commander too?

**Comment by dmicsa** [comment]
I don't compile/use Pascal. :(

DC guys answered this in this post: https://doublecmd.sourceforge.io/forum/viewtopic.php?f=6&t=4771&p=24797#p24797

**Comment by dmicsa** [comment]
Is this issue solved? Why is closed if is not solved?

**Comment by Alexey-T** [comment]
No work on it from DC developers so I closed; I will reopen for a month, will wait for DC devs help

**Comment by Alexey-T** [comment]
Idea#2: plugin's Lazarus conflicts with DCmd's Lazarus.
TotalCmd author has solved it:
it replaced string in this Laz function
```
function FindControl(Handle: HWND): TWinControl;
begin
  if Handle <> 0
  then Result := TWinControl(GetProp(Handle,'WinControl'))
  else Result := nil;
end;
```

**Comment by dmicsa** [comment]
TY Alexey. I posted your reply to their forum.

**Comment by Alexey-T** [comment]
no feedback, closing.

**Comment by dmicsa** [comment]
ty for closing it still crashes.
