### ISSUE TITLE
[suggestion] начальный размер экрана

### ISSUE THREAD

**Issue by rg-software** [Alexey-T/CudaLister#38]
На мой взгляд, начальное окно CudaLister очень маленькое для большинства современных экранов (700*700). Может, сохранять размер, установленный пользователем?

**Comment by ildarkhasanshin** [comment]
у меня 800х580
cudatext 1.66
ubuntu 18.04

**Comment by Alexey-T** [comment]
CudaLister или CudaText?? Lister - тогда за это отвечает Тотал а не я

**Comment by rg-software** [comment]
Да, Вы правы, если выставить окно в желаемый размер, а потом сохранить позицию через меню Вид, всё работает.
