### ISSUE TITLE
ts files are not highlighted

### ISSUE THREAD

**Issue by sgaliamov-albelli** [Alexey-T/CudaLister#44]
Hello!
I downloaded lexers for TypeScript from https://sourceforge.net/projects/synwrite-addons/files/Lexers/.
Unzipped it into lexers folder.
But when I press `ctrl+q` there is no higlighting in ts files at all.
What I'm doing wrong?

**Comment by Alexey-T** [comment]
If you unzipped file lexer.TypeScript.zip to lexers folder, it should work
Does it work with other lexers? LESS/ YAML?

**Comment by sgaliamov-albelli** [comment]
да, работает, я подкрутил TypeScript.lcf для tsx и оно работает:
```
  Extentions = 'ts str tsx'
````
![image](https://user-images.githubusercontent.com/47250838/56197309-d933da80-6038-11e9-99ad-3bb1c2658789.png)

str был там изначально.
для ts файлов как-будто листер вообще не подгружается.
![image](https://user-images.githubusercontent.com/47250838/56197286-ca4d2800-6038-11e9-970e-6fed5e6c368e.png)

**Comment by Alexey-T** [comment]
Может не подгружаться если там двоичные символы <32

**Comment by Alexey-T** [comment]
В CudaText с лексером тем же , файл открывается?

**Comment by Alexey-T** [comment]
Прикрепите два файла- один я посмотрю про html tags, второй для открыть

**Comment by sgaliamov-albelli** [comment]
[commonProps.txt](https://github.com/Alexey-T/CudaLister/files/3084109/commonProps.txt) нужно поменять расширение на ts, чтоб попробовать.
с расширением txt листер подргужается, с контеном все впорядке:
![image](https://user-images.githubusercontent.com/47250838/56199048-675d9000-603c-11e9-8c22-19406b5db3d1.png)
CudaText работает корректно:
![image](https://user-images.githubusercontent.com/47250838/56199106-89efa900-603c-11e9-9ac1-7b1d092e8437.png)
дело похоже в том, что ts файлы просто игнорируются.
других плагинов не установлено. версия TC 9.21a.
на другой машине такое же поведение.

**Comment by Alexey-T** [comment]
@kvichans @iramsoft Не могли бы подтвердить это, на плагине CudaLister?

**Comment by Alexey-T** [comment]
.ts это еще и видео-файлы. Может какой плагин для видео мешает..

**Comment by Alexey-T** [comment]
проверил в TC 9.22. тотал вообще не дергает плагин для .ts files. плагин не виноват. TC issue.
