### ISSUE TITLE
Options Dialog with 4K monitor

### ISSUE THREAD

**Issue by JBerry910** [Alexey-T/CudaLister#45]
The options dialog box is present; however, it is almost impossible to read/navigate.  See attached.
Using Windows 10 [Version 10.0.17134.765]; CudaLister v1.6.7 on an HP laptop set up with the defaults as indicated by HP.
[CudaListerOptions.pdf](https://github.com/Alexey-T/CudaLister/files/3193252/CudaListerOptions.pdf)

**Comment by Alexey-T** [comment]
Thanks, to fix.

**Comment by Alexey-T** [comment]
fixed. Upd at totalcmd.net site.

**Comment by JBerry910** [comment]
Works perfectly.  Thank you for your prompt attention.

Support of this nature is beyond compare. Thank you again for the fix and for great software products.

Joe Berry

________________________________
