### ISSUE TITLE
Не работает "Find" (plugin v. 2019.05.18)

### ISSUE THREAD

**Issue by divlv** [Alexey-T/CudaLister#48]
В версии плагина от 2019.05.18 непонятно как вызвать меню "Find".
При нажатии на пункт всплывающего меню "Find", указатель мышки мигает, но ничего не происходит.
Было бы, конечно, идеально, если бы это меню вызывалось с помощью "горячих" клавиш.
(Windows 8 eng, Unreal Commander v. 3.57 64bit)

**Comment by Alexey-T** [comment]
Только в Тотал Командер тестирую. Там то работает ?
