### ISSUE TITLE
Crashes on selection

### ISSUE THREAD

**Issue by GeorgeMakarov** [Alexey-T/CudaLister#49]
Lister and TC crashes if while text selection I move cursor out of lister window

**Comment by Alexey-T** [comment]
I cannot see it on x32 and x64 versions.
@kvichans: can you test please?

**Comment by kvichans** [comment]
Не пользуюсь CudaLister

**Comment by Alexey-T** [comment]
@iramsoft can you reproduce the bug?

**Comment by iRamSoft** [comment]
На x64 не повторяется. Драг не крашит окно.

@GeorgeMakarov, can you record your actions that lead to the indicated error?

**Comment by Alexey-T** [comment]
Closing

**Comment by GeorgeMakarov** [comment]
![cudalister crashing](https://user-images.githubusercontent.com/24646716/63344475-1a3f5100-c383-11e9-9ce5-03577a9b92f8.gif)

Sorry for late reply, i was on business trip
