### ISSUE TITLE
cannot see thmes in  [options dialog...] -> [Theme - UI...] dialog box.

### ISSUE THREAD

**Issue by colemanlee** [Alexey-T/CudaLister#50]
Hi,
when I click [options dialog...] -> [Theme - UI...] dialog box, it shows nothing in the list, how to choose themes?
I have these themes in the folder "cudalister\themes":

- amy.cuda-theme-syntax
- cobalt.cuda-theme-syntax
- darkwolf.cuda-theme-syntax
- ebony.cuda-theme-syntax
- green.cuda-theme-syntax
- navy.cuda-theme-syntax
- sub.cuda-theme-syntax
- zeus.cuda-theme-syntax
- amy.cuda-theme-ui
- cobalt.cuda-theme-ui
- darkwolf.cuda-theme-ui
- ebony.cuda-theme-ui
- green.cuda-theme-ui
- navy.cuda-theme-ui
- sub.cuda-theme-ui
- white.cuda-theme-ui
- zeus.cuda-theme-ui
- Zeus-CudaText.license.txt

OS version: Microsoft Windows 10 ver 1903
TotalCommander version:9.22a x64

![PIC__52](https://user-images.githubusercontent.com/10258421/64899526-69487f80-d6be-11e9-9073-1d865ad66361.jpg)

**Comment by Alexey-T** [comment]
I checked it on release of plugin, and it show ok here...

**Comment by colemanlee** [comment]
> I checked it on release of plugin, and it shows ok here...
I found the reason, the file path of CudaLister should be all English. If the path has non-English words such as Chinese characters, CudaLister will create a gibberish folder name such as "30_ϵͳС����" and store [CudaLister] section to this gibberish folder. 
There are no theme files in this folder so it can not show themes in [Theme - UI...] dialog box.
Can you update the source code to support non-English path?

**Comment by Alexey-T** [comment]
I thiunk it depends on FreePascal version, i used the laters FPC version in CudaLister 1.6.9: still this bug?

**Comment by colemanlee** [comment]
> I think it depends on FreePascal version, i used the last FPC version in CudaLister 1.6.9: still this bug?

Yes, I have this bug in newest version of CudaLister.

![PIC__57](https://user-images.githubusercontent.com/10258421/64907222-2ae4ac00-d722-11e9-84c4-a0b67e0875a2.jpg)
![PIC__58](https://user-images.githubusercontent.com/10258421/64907266-ad6d6b80-d722-11e9-8c1d-454271def157.jpg)

**Comment by Alexey-T** [comment]
TC 9.22a cannot work ok if I rename its folder Totalcmd to Unicode Indian name, all lister plugins are lost

**Comment by colemanlee** [comment]
> TC 9.22a cannot work ok if I rename its folder Totalcmd to Unicode Indian name, all lister plugins are lost
I have changed my folder path to English.
Thank you all the same.
