### ISSUE TITLE
1.6.9 При смене лексера игнорируется lexmap

### ISSUE THREAD

**Issue by podsfg** [Alexey-T/CudaLister#51]
Версия: 1.6.9
Theme - UI = ebony
Theme - syntax = solarized dark

При смене лексера не подхватывается lexmap у подменного лексера.

Например, есть:

1. SQL.cuda-lexmap
2. MySQL SQL.cuda-lexmap
3. SQL.lcf
4. MySQL SQL.lcf

В двух lexmap Symbol=Symbol.

В теме Solarized dark:
```
"Lex_Symbol" : {
"Type" : 1,
"Styles" : "",
"CFont" : "#FF7480",
"CBack" : "",
"CBorder" : "",
"Border" : "0,0,0,0"
},
```
SQL.lcf
```
item
DisplayName = 'Symbol'
Font.Charset = DEFAULT_CHARSET
Font.Color = clMaroon
Font.Height = -13
Font.Name = 'Courier New'
Font.Style = [fsBold]
end
```
MySQL SQL.lcf
```
item
DisplayName = 'Symbol'
Font.Charset = DEFAULT_CHARSET
Font.Color = clMaroon
Font.Height = -13
Font.Name = 'Courier New'
Font.Style = []
end

```

У двух одинаковое расширение для открытия. Открываю любой файл sql, по умолчанию открывается с лексером MySQL SQL.lcf и стилем, который установлен в lexmap и темой (solarized dark).
В открытом файле меняю лексер (в нижней части окна кликаю на название лексера и выбираю из списка) на SQL и стиль уже берется из самого SQL.lcf, игнорируя SQL.cuda-lexmap.

То есть при первичном открытии цвет символа будет "#FF7480", а при смене лексера цвет изменится на clMaroon,

В CudaText все воспроизводится корректно при смене лексера.

**Comment by Alexey-T** [comment]
fixed. спасибо. Мне нравится как написан репорт. пишите репорты по CudaText, буду рад.
