### ISSUE TITLE
1.6.10 Кодировка "cp1252" при открытии

### ISSUE THREAD

**Issue by podsfg** [Alexey-T/CudaLister#52]
Спасибо за ваш труд!
Версия: 1.6.10
ОС:Microsoft Windows Seven x64 Professional Edition Version 6.1 (build 7601) Service pack 1
Total Commander(x64) 9.22a

Файл при просмотре открывается по умолчанию с кодировкой "**cp1252**", кириллица из-за этого становится не читаемой.

P.S. Только что увидел, что на форуме TC Flasher уже об этом написал плюс еще его другие замечания.

**Comment by Alexey-T** [comment]
поправил.
