### ISSUE TITLE
1.6.10.1 Плагин не отрабатывает, если есть символ "x07"

### ISSUE THREAD

**Issue by podsfg** [Alexey-T/CudaLister#53]
Версия: 1.6.10.1
Плагин не подгружается, если в тексте есть определенный символ, похож на: Unicode character U+2022 (bullet).
Текстовый файл, кодировка ANSI.
[Файл для воспроизведения - test.txt](https://github.com/Alexey-T/CudaLister/files/3656237/test.txt)

В CudaText этот символ отображется как "x07"

**Comment by OmlineEditor** [comment]
Ну этот символ до сих пор так и отображается, почему закрыти тикет, разве проблема решена?
В Notepad++ символ нормально показывается. Может в программе не до конца реализована поддержка Unicode?

**Comment by Alexey-T** [comment]
слушайте, если он отображается как x07 то проблема РЕШЕНА. потому что проблема-= когда файл не открывался.
