### ISSUE TITLE
1.6.10.1. Раздел "Файл". Не работают команды "Перечитать файл F2" и "Печать Ctrl + P"

### ISSUE THREAD

**Issue by podsfg** [Alexey-T/CudaLister#54]
Версия: 1.6.10.1
Разрядность: x32, x64

При нажатии на F2 (Перечитать файл) содержимое не обновляется.
При нажатии на Ctrl+P (Печать...) окно параметров печати не появляется.

Например,
1. Создаем текстовый файл в блокноте, записываем туда значение "1" и сохраняем.
2. Заходим в TC и открываем этот файл по F3 в плагине, - видим значение "1". Lister с этим файлом оставляем открытым.
3. Переходим обратно к файлу в блокноте, - обновляем значение , например "12" и сохраняем (Ctrl + S).
4. Возвращаемся к TC и нажимаем кнопку "F2" или вызываем из меню "Файл - Перечитать файл F2" у нашего открытого файла - ничего не происходит.
5. Переключаемся на стандартный Lister (Вид - Только текст 1) - данные обновились.

В стандартном листере (Только текст) при нажатии F2 данные обновляются и параметры печати отображаются.

**Comment by Alexey-T** [comment]
Print вообще не реализован никак
Reload- to fix

**Comment by Alexey-T** [comment]
Reload - есть такое но плагин не виноват , это ТС не дёргает плагин. Гислеру написал , жду.

**Comment by Alexey-T** [comment]
Гислер не ответил, напишите ему сами, лучше через офф форум Тотала.

**Comment by podsfg** [comment]
Понял, спасибо!
