### ISSUE TITLE
Crashes on selection

### ISSUE THREAD

**Issue by GeorgeMakarov** [Alexey-T/CudaLister#55]
![63344475-1a3f5100-c383-11e9-9ce5-03577a9b92f8](https://user-images.githubusercontent.com/24646716/67652092-4ec42000-f965-11e9-9e8b-d37d7b37e4b7.gif)

В продолжение тикета "Crashes on selection #49", который был закрыт

**Comment by Alexey-T** [comment]
не повторил. на х32 и х64 билде.
таскал мышь по тексту выводя ее за окно Листера. отпускал за окном или нет. и слева и справа за окном.
дайте точные шаги повтора.
у меня Вин10 х64.

**Comment by GeorgeMakarov** [comment]
Использую TC 9.0a 64-bit
Win10 x64 build 17763.805
версия CudaLister от 2019.05.18
Начинаю выделение, если курсор во время выделения попадает за пределы окна, то TC крашится
Могу попробовать на версии, в которой есть дополнительный выхлоп диагностики, если таковая имеется

**Comment by Alexey-T** [comment]
Total Commander, Version 9.22a- последний, надо пробовать его.
CudaLister тоже надо последний с wincmd.ru!

**Comment by GeorgeMakarov** [comment]
с версией TC 9.22а и CudaLister от 24.09.19 проблема не наблюдается. Спасибо за поддержку
