### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by alinaimi** [Alexey-T/CudaLister#58]
Editing and saving need a lot of unnecessary user inputs. Two suggestion that can be stored in lsplugin.ini:

- always opens at NOT read-only (or at least for files smaller than a specific size)
- CTL+S to save edits

Another option is to add a toolbar similar to Cudatext.

Thanks for your great work!

**Comment by Alexey-T** [comment]
>    always opens at NOT read-only (or at least for files smaller than a specific size)
>    CTL+S to save edits

I may add this, as exchange. see my reply in #61 please.

**Comment by Alexey-T** [comment]
editing+saving is disabled now. sorry.
