### ISSUE TITLE
END or CTRL+END don't respect "Show last line on top" setting when caret is not turned off

### ISSUE THREAD

**Issue by elgonzo** [Alexey-T/CudaLister#59]
END and CTRL+END don't seem to respect "Show last line on top" being enabled if caret is not hidden. (I'll file a new issue for that...)

Only when the caret is turned off (by enabling "**No caret, scroll by arrows/Home/End/Space/Shift+Space**" checkbox), END and CTRL+END  will respect the "Show last line on top" setting and behave accordingly.

**Comment by Alexey-T** [comment]
it's very minor issue and not a bug. when caret is off, it's almost ok behaviour.
