### ISSUE TITLE
Wrong clipboard behaviour

### ISSUE THREAD

**Issue by krasnovpro** [Alexey-T/CudaLister#60]
Sometimes, when I disable the 'read-only' flag and trying to paste data from the clipboard, it pastes some very old string, not actual clipboard data.

**Comment by Alexey-T** [comment]
Windows API givves such a string to plugin. I cannot control contents of this.

**Comment by krasnovpro** [comment]
All other plugins and apps don't have such issue.

**Comment by Alexey-T** [comment]
maybe you can install Lazarus IDE and repeat this issue in its 'source editor'? then we can post bugreport to them.

**Comment by Alexey-T** [comment]
solved by PR #101 seems.
