### ISSUE TITLE
Disable read-only by default

### ISSUE THREAD

**Issue by krasnovpro** [Alexey-T/CudaLister#61]
Add an option to turn off read-only by default

**Comment by Alexey-T** [comment]
IMO not a good option for lister, user may change the file by mistake.
let's do exchange.
I will add this option, for exchange: for a youtube video about CudaText (not small) / blog post about CudaText (not small).

**Comment by OmlineEditor** [comment]
add hotkey a quick toggle disable or add a button at the bottom of the status bar.

![1](https://user-images.githubusercontent.com/13348933/116631433-c8bfd580-a95d-11eb-86df-6bd5b5949f5b.PNG)

**Comment by Alexey-T** [comment]
симнительно это hotkey. юзеру надо помнить какой-то левый hotkey. лучше уж меню вызвать.

**Comment by OmlineEditor** [comment]
> лучше уж меню вызвать.

Меню вызывается мышкой, а это более долгий процес если ты используешь только клавиатуру, Я например мышку почти не использую в Total Commander'e. И если человек захочет от вызовет меню, его же никто не заставляет учить hotkey. Это только для тех кому нужно, мне бы пригодилось например, и возможно кому-то еще тоже пригодится.

**Comment by krasnovpro** [comment]
Хаха

**Comment by Alexey-T** [comment]
maybe not. read-only will be always on.
