### ISSUE TITLE
File -> Reload file / F2 not working

### ISSUE THREAD

**Issue by mnerec** [Alexey-T/CudaLister#62]
Reloading a file that has changed by clicking "File -> Reload file" or pressing the F2 key is not working for me. The lister is unchanged even though the file has been changed since loading.

Using Total Commander (x64) 9.51 with CudaLister v1.6.16.0.

**Comment by Alexey-T** [comment]
so CudaLister must handle F2 by itself and reload file?

**Comment by mnerec** [comment]
I just noticed that F2 is not working in CudaLister, while it works in the default lister.

Whether you're supposed to respond to F2 manually or Total Commander is supposed to call ListLoad/ListLoadNext when pressed, I don't know and I cannot find any mention of it in [WLX-SDK docs](https://github.com/ghisler/WLX-SDK/tree/master/docs)

Maybe your question should be forwarded to Ghisler. He should know :-)

**Comment by Alexey-T** [comment]
fixed for F2 hkey (but not for menu item of Lister).
