### ISSUE TITLE
Recognize local file:///c:/folder/file.txt URL

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [Alexey-T/CudaLister#63]
It would be nice if CudaLister was able to recognize a local file URL (e.g. `file:///c:/Tools/Links/GitHub.appref-ms` or `file:///d:/temp/Ger%E4te/Kopfh%F6rer/Fliegen%20🛩%20%B7%20King%AE%20(1).txt` or `file:///d:/temp/Ger%E4te/Keine%20Kunst/梁胜男.jpg`) and open the corresponding link, as is the case with http(s).

**Comment by Alexey-T** [comment]
Plugin exists for this!
http://synwrite.sourceforge.net/forums/viewtopic.php?f=19&t=2597

**Comment by Alexey-T** [comment]
Related (not links highlight)

1.125.0 (2021/02)

+ add: auto-completion for file URI file:///, controlled by new option "autocomplete_file_uri"
+ add: Wiki topic https://wiki.freepascal.org/CudaText#File_URI_auto-completion

**Comment by ThomasHeinrichSchmidt** [comment]
Had a look at [GitHub cuda_file_uri_handler](https://github.com/halfbrained/cuda_file_uri_handler) but could not find out how to make this usable for the Total Commander CudaLister.

**Comment by Alexey-T** [comment]
CudaLister..... ops, sorry. It has no support for this. no plan to add this in here.

**Comment by ThomasHeinrichSchmidt** [comment]
Then be it so.
