### ISSUE TITLE
exception 'control has no parent window' on Unicode C# file

### ISSUE THREAD

**Issue by OmlineEditor** [Alexey-T/CudaLister#65]
use: cudalister 1.6.21 x86 and cudalister 1.6.20 x86 
TC: 9.51
Windows 7 x64

I open a long text in C# and try to rewind it with the mouse. an error window appears, sometimes at the very beginning of the text, sometimes at the very end of the text.
I think the problem is that it doesn't understand the syntax and doesn't understand some of the characters in the comment.
see the file in the archive: [bug.zip](https://github.com/Alexey-T/CudaLister/files/6402427/bug.zip)

![err](https://user-images.githubusercontent.com/13348933/116628689-58fb1c00-a958-11eb-8d40-1fd263a72e5a.png)

**Comment by Alexey-T** [comment]
strange bug. I will try it on win10 later. (I am on linux)

**Comment by Alexey-T** [comment]
текущая кодовая база уже другая- старые версии cudalister были на старой базе. а на текущей базе я это не повторил. и еще затык-- текущая версия пока не показывает syntax подсветку, я пока не смог это поправить.

**Comment by OmlineEditor** [comment]
Если переименовать два файла из архива в 1.txt и 2.txt чтобы подсветки синтаксиса не было, то программа все равно выдает ошибку. Может там не только проблема в подсветке для C#?

**Comment by Alexey-T** [comment]
я пробовал сегодня- подстветки не было, креша тоже не было. дело там в кодировке, но пока повтора нет.

**Comment by Alexey-T** [comment]
это уже на новой кодовой базе было.

**Comment by Alexey-T** [comment]
да, старая.
не ранее чем через неделю наверно.

**Comment by OmlineEditor** [comment]
> не ранее чем через неделю наверно.

В ближайшее время планируется выпусить новую версию плагина? Уже 4 месяца жду и надеюсь на лучшее. Плагин по прежнему иногда падает с ошибкой т.к. старая версия.

**Comment by Alexey-T** [comment]
пока нет. не могу сделать рабочую, при работе в среде Тотала компонент сбоит. его threads сбоят.

**Comment by Alexey-T** [comment]
сбоят так что любое редакт-е дает рассинхрон. подсветка теряется.

**Comment by OmlineEditor** [comment]
> сбоят так что любое редакт-е дает рассинхрон. подсветка теряется.

А если только просмотр файла без редактирования, все нормально?

**Comment by Alexey-T** [comment]
да, так нормално. но это недоплагин уже.

**Comment by OmlineEditor** [comment]
ну зато он хотябы перестал падать в режиме просмотра, это главное. Давайте выпустим новую версию и потом напишем о проблеме разработчику Total Commander'a возможно вашей вины тут нет и проблему исправят в новой версии TC.

**Comment by Alexey-T** [comment]
хорошо, уговорили, скоро соберу сборку...

**Comment by Alexey-T** [comment]
[wlx_cudalister_1.7.0.zip](https://github.com/Alexey-T/CudaLister/files/7112291/wlx_cudalister_1.7.0.zip)

вот файлы. правки пока не запрещены, если надо -сделаю. посмотрите эту версию.

**Comment by OmlineEditor** [comment]
полное тестирование займет время, из того что щас бегло удалось найти это глюк с отображением ссылок.
открываю файл [bug.zip](https://github.com/Alexey-T/CudaLister/files/7112358/bug.zip), все данные помещаются на оной странице, по привычке пытаюсь перематывать нажимая на клавиши PageUp и PageDown, курсор перепрыгивает в самый конец и при этом пропадает подсветка ссылкок на сайты.

Кстати размер планига стал немного меньше. вы что повырезали часть кода? Я думала наоброт что-то новое добавите.
И еще просьба, вы можете выложить версию в релиз чтобы все видели ее, пусть будет версия beta чтобы все знали. Может кто-то еще посмотрит на плагин и найдет что-то что можно улучшить или исправить.

**Comment by Alexey-T** [comment]
нет, не вырезал. но апдейт моего IDE может такое дать.

повторил с ссылками. даже на Cudatext.

**Comment by Alexey-T** [comment]
баг с ссылками- fixed. завтра выложу публик-версию (не точно).

**Comment by Alexey-T** [comment]
закрываю, т.к. пошел оффтопик. прололжим в новых issue.
