### ISSUE TITLE
Render EOL unprinted char as 'paragraph'

### ISSUE THREAD

**Issue by OmlineEditor** [Alexey-T/CudaLister#66]
Сейчас в программе символ новой строки в виде стрелки:  ↓
Можно сделать выбор или поменять на стандартный символ как в других программах? А то очень не привычно.
![изображение_2021-04-30_024713](https://user-images.githubusercontent.com/13348933/116631803-5dc2ce80-a95e-11eb-9857-86d7792ac09a.png)

**Comment by Alexey-T** [comment]
а в каких других то? дайте пример или скрин. причем вы сказали "других" так что дайте два примера!

**Comment by OmlineEditor** [comment]
Ну вот в стандартном Word'e в котором сижу 90% времени формляя бумажки и где эти символы уже привычны глазу
![word](https://user-images.githubusercontent.com/13348933/116737667-26096480-a9fa-11eb-8435-d5870b1ab143.PNG)


И вот еще SynWrite которым на работе пользуюсь. Дома Notepad++ но там только привычный символ ¶ на панеле задач, а в самом приложении показывают целиком символы новой строки и перевода каретки в виде букв: CR LF
![SynWrite](https://user-images.githubusercontent.com/13348933/116737743-43d6c980-a9fa-11eb-97f5-74c110e6662a.PNG)

**Comment by Alexey-T** [comment]
хорошо, вы меня убедили, стоит сделать опцию видимо. в CudaText сначала. плаг пока не могу.

**Comment by Alexey-T** [comment]
linked issue https://github.com/Alexey-T/CudaText/issues/3362
