### ISSUE TITLE
Impossible to return to the Default Theme

### ISSUE THREAD

**Issue by yozhic** [Alexey-T/CudaLister#72]
После установки CudaLister 1.6.21 содержимое окна плагина отображается в цветовой гамме темы по умолчанию. В окне настроек `Theme UI` эта тема обозначена знаком «дефис» (_если я правильно понял_). Если хотя бы раз переключиться на любую другую тему UI, то обратное переключение на тему по умолчанию становится невозможным. Пример воспроизведения:  

1) включена тема `cobalt`;  
2) вызываю окно настроек `Theme UI`;  
3) выбираю верхнюю строчку со знаком «дефис»;  
4) перезагружаю плагин;   
5) ничего не происходит, цветовая палитра не меняется, остаётся по-прежнему `cobalt`, хотя в окне настроек и в соответствующих ini-строках значится «дефис», т.е. по умолчанию.

**Comment by Alexey-T** [comment]
нет повторения. закрываю.
