### ISSUE TITLE
Not open file in cudalister by default and not see spec char as BS

### ISSUE THREAD

**Issue by HarDX** [Alexey-T/CudaLister#75]
If i open file with special char - as hex **08** it not open in cuda.
It opened in builtin lister.
If force in menu cudalister - open this file - it opened - but not see this char

This is as in VScode:
![photo_2021-12-07_13-52-25](https://user-images.githubusercontent.com/5231223/145030618-d3b94c14-e161-4df8-98e3-ccd53a788294.jpg)
In hex:
![photo_2021-12-07_17-39-08](https://user-images.githubusercontent.com/5231223/145030622-a40e0de5-0d20-46c3-b3c0-2546a1179d17.jpg)
In cuda force opened file:
![photo_2021-12-07_17-39-12](https://user-images.githubusercontent.com/5231223/145030624-e3791297-c5e9-412e-9bed-ce7ea187eb01.jpg)
In total cmd (as opened thi file by default)
![2021-12-07_174110](https://user-images.githubusercontent.com/5231223/145030927-2705d39a-27de-4f85-989e-74f27ef48b9e.jpg)

**Comment by Alexey-T** [comment]
Please attach this file.

**Comment by HarDX** [comment]
[log1.log](https://github.com/Alexey-T/CudaLister/files/7668565/log1.log)

**Comment by Alexey-T** [comment]
CudaText shows it ok, will adjust the plugin, wait pls
![Screenshot from 2021-12-07 16-26-00](https://user-images.githubusercontent.com/4154978/145037384-2812529d-479a-424a-b99c-74d54a7cd82f.png)

**Comment by Alexey-T** [comment]
The plugin avoids this file because of 0x08 char, it is char not for text files. if I enable 0x08 char, later some user will ask about 0x07, then 0x06 etc. how did you get 0x08 char in a text file?

**Comment by HarDX** [comment]
> how did you get 0x08 char in a text file?
raw log file from telnet/ssh session

**Comment by Alexey-T** [comment]
Fixed... but I don't make the release, problems with threads is big.
