### ISSUE TITLE
Option to set "Word wrap" by default

### ISSUE THREAD

**Issue by mrkingmidas** [Alexey-T/CudaLister#79]
Hello!

Please, add option to set "Word wrap" by default - in Double Commander no menu option "word wrap" and every time needs to click mouse on status bar or right click menu

**Comment by Alexey-T** [comment]
Maybe later, I don't use the Totalcmd plugin now.

**Comment by dvygolov** [comment]
Can you please tell, how to make these option to be set by default? what should be done and where?

**Comment by Alexey-T** [comment]
I am on linux. as I see the code in Options form,
```
  chkWrap.Checked:= ed.OptWrapMode<>cWrapOff;
```
Options dialog has the checkbox option!
```
  object chkWrap: TCheckBox
    Left = 424
    Height = 19
    Top = 256
    Width = 134
    Caption = 'Word-wrap by default'
    OnChange = chkWrapChange
    TabOrder = 21
  end
```
