### ISSUE TITLE
Crash if N CudaLister windows are opened, on closing one of em

### ISSUE THREAD

**Issue by OmlineEditor** [Alexey-T/CudaLister#82]
В последней версии плагина  1.7.2 есть ошибка и она немного глючит.
Для повторения ошибки использовать поседний Total Commander 10.00 final
- открыть текстовый файл на F3 (файл должен поддерживать плагином)
- видим, что все открылось и возвращаемся в TC, открытый файл **_не_** закрываем
- примерно 2-3 минуты мы используем TC, открываем на F3 другие файлы и закрываем их, **_не_** прикасаясь к открытому файлу на F3
- обильно лазим по папкам и делаем вид бурной деятельности в TC
- через 2-3 минуты  возвращается к файлу, открытому на F3, и закрывает его, нажав на крестик (или жмем Esc)
- появляется ошибка нарушения доступа 

![TC](https://user-images.githubusercontent.com/13348933/159296756-918a8605-ce74-4bfb-ba8d-20b403266a5e.PNG)

Старая версия 1.6.21 работает без ошибки.
Можете найти ошибку и исправить ее?

**Comment by Alexey-T** [comment]
получается что с точки зрения моего плага, ничего в нем вы не делали? тольоко открыли, потом ушли-пришли, и закрыли? тогда это видимо проблема в ТС, попробуйте перевести ваш репорт в google translate и запостить на оффорум ТС.

**Comment by Alexey-T** [comment]
хорошо, я кажется знаю что делать. была правка которая несовместна с тем что мы можем открыть Н окон плагина.

**Comment by Alexey-T** [comment]
стало хорошо вроде бы. пробуйте 1.7.3.

**Comment by OmlineEditor** [comment]
Кажется не падает, но есть проблема. 
при попытке открыть .php файл подсветка не работает вообще, закрываю его и открываю 2й раз и падает полностью весь TC.
Проблема в файле подсветки синтаксиса, вы там что-то поменяли и оно перестало работать. Если заменить на старую  версию 1,6,21 подсветки синтаксиса php то все норм.

Прошу поправить подсветку синтаксиса для .php
