### ISSUE TITLE
Folding lines are not displayed

### ISSUE THREAD

**Issue by yozhic** [Alexey-T/CudaLister#83]
При вызове плагина не отображаются линии фолдинга.

Как воспроизвести:
1. Выделяем файл, жмём `Ctrl+Q`, открывается быстрый просмотр в боковой панели. Линии фолдинга не отображаются.
2. Вызываем диалог настроек плагина. Сразу же закрываем этот диалог. Линии фолдинга начинают отображаться.
3. Закрываем быстрый просмотр. Снова вызываем его по `Ctrl+Q`. Линии фолдинга опять не отображаются.

Моя конфигурация:
Windows 10 x64 (21H2 Enterprise, build 19044); Total Commander 10.00 32-bit; CudaLister 1.7.4.

Примечание 1. Если смотреть внимательней, то видно, что линии начинаются отображаться в момент вызова диалога настроек.

Примечание 2. Проблема появилась начиная с версии 1.7.0. В версии 1.6.12 линии при вызове отображаются.

Примечание 3. На анимации видно, что помимо линий фолдинга не подсвечиваются блоки комментариев. После вызова диалога настроек и они также начинают отображаться.

Примечание 4. На TC x64 та же проблема.

Анимация:
![CudaLister_FoldLines_issue](https://user-images.githubusercontent.com/13917732/159523861-3f1ca29d-ad35-41aa-a67c-1883e6784808.gif)

**Comment by Alexey-T** [comment]
подтверждаю. пока не могу поправить, буду работать еще.

**Comment by OmlineEditor** [comment]
Если на F3 жать при простом просмотре тоже линий нет, не только на Ctrl+Q

**Comment by Alexey-T** [comment]
Пробуйте на новом релизе,у меня вроде бы и линии стали ОК и файл красится после открытия (до этогго красился не всегда)

**Comment by yozhic** [comment]
Теперь всё отлично, спасибо!

**Comment by Alexey-T** [comment]
@OmlineEditor @yozhic 
вот бета с разрешенным редиктированием. снова. попробуйте. там есть лагание, это не могу поправить. если вам ОК то пойдет в следующий релиз.
[wlx_cudalister_1.7.5.zip](https://github.com/Alexey-T/CudaLister/files/8351740/wlx_cudalister_1.7.5.zip)

**Comment by yozhic** [comment]
Попробовал. 
1. Линии фолдинга, прокрашивание — полёт нормальный. Лаг наблюдается, но если бы вы не сказали, то я бы сам внимания даже не обратил. Выглядит всё в рамках обусловленного загрузкой. Маленький лаг наблюдается только по `Ctrl+Q`. По `F3` всё гладко (Листер чуть дольше загружается и потому ничего не заметно). 
2. Хоткей `Ctrl+R` для переключения на редактирование не работает. Переключиться можно только из контекстного меню ПКМ.

**Comment by Alexey-T** [comment]
Ctrl+R поправил, вот
[wlx_cudalister_1.7.5a.zip](https://github.com/Alexey-T/CudaLister/files/8351857/wlx_cudalister_1.7.5a.zip)

**Comment by yozhic** [comment]
Я тоже поторопился: открыл Issue про немигающий курсор.

**Comment by Alexey-T** [comment]
вижу что не мигает.
виду что работает Ctrl+Shift+R вместо Ctrl+R. не понимаю причину. отладчик не показывает.
