### ISSUE TITLE
not jumping to the next found match when searching

### ISSUE THREAD

**Issue by adoeller** [Alexey-T/CudaLister#86]
When doing a search, e.g. "information" and pressing f3 to jump to the next match. the match may be invisible under the horizontal scrollbar. only a slight dark line can be seen in the screenshot

![grafik](https://user-images.githubusercontent.com/45470571/161632823-a8e233f7-8814-4d97-b882-957e81aa31fb.png)

**Comment by Alexey-T** [comment]
version 1.7.5.4 released. it has NEW scrollbars which may fix it. option for new scrollbar.
and if not -- just set new option "caret proximity" to e.g. 2-3.

**Comment by adoeller** [comment]
works fine now. thanks
