### ISSUE TITLE
Request: replace the "each nth" line number setting with a free selection

### ISSUE THREAD

**Issue by Kaens** [Alexey-T/CudaLister#90]
For example, "each nth" radiobuttons could be replaced by "user-defined" which would show a natural number selector. Do that by default with the values of 1 or 0 for "all" or "none", and you won't need anything else.
"Relative" doesn't currently have that freedom, but it could if we had such a control handy.
(I like them grouped by 4!)

**Comment by Alexey-T** [comment]
Base component didn't support any natural num, sorry, I decline tthe wish
