### ISSUE TITLE
Question - Bash files Autoopen without .sh

### ISSUE THREAD

**Issue by masterwishx** [Alexey-T/CudaLister#95]
Thanks for great plugin for TC.
is any way i can autoview bash files with no .sh (no extantion at all) but having #!/bin/bash at first line ? 
i dont have recognise it like bash file
should i add to str1=#!/bin/bash in Bash script.cuda-lexmap ?
or add Extentions = "" in Bash script.lcf ?
what is the right way ?

**Comment by Alexey-T** [comment]
No, this is not supported yet.

**Comment by masterwishx** [comment]
are you planning to fix it in future maybe ?

**Comment by masterwishx** [comment]
Thanks for Update , how exactly i can it now ?

**Comment by masterwishx** [comment]
any news about it ?

**Comment by Alexey-T** [comment]
Auto detection of Bash files exists in my text editor CudaText. i don't plan to add the similar detection to CudaLister. but you can try to make the patch.

**Comment by masterwishx** [comment]
> but you can try to make the patch.

Dont really know how to make it :(
