### ISSUE TITLE
No caret mode: End + PgUp returns to beginning of the file

### ISSUE THREAD

**Issue by CaptainFlint** [Alexey-T/CudaLister#96]
1. Configure CudaLister to run in No caret mode.
2. Open some file that is longer than 3 pages.
3. Press End to jump to the end of the document.
4. Press PageUp.

Result: the scroll position returns back to the very beginning of the file, and not one page up from the end, as expected.

**Comment by Alexey-T** [comment]
Do you see it also in CudaText (no 'no caret' there)? I see it. and it is ok there. after Ctrl+End ('go to text end') I see scrollbar 2 pages down. 1 pageup - scrollbar in  the beginning. OK because on the last position, we did not scroll last line to the top

**Comment by CaptainFlint** [comment]
Both in CudaText and in CudaLister with "no caret" mode turned off the issue is not reproduced. If I open a big file (let's say, history.txt from TC), press Ctrl+End, Cuda jumps to the end of the file. If I then press PageUp, the cursor jumps one screen up from that position. In other words, it works exactly as expected from the PageUp key.

But in CudaLister in "no caret" mode, if I press End (or Ctrl+End), and then PageUp, I do not go up just one page, but to the very beginning, the first line of the file. So PageUp in this situation works like Home (or Ctrl+Home), which is wrong.

**Comment by CaptainFlint** [comment]
Thank you for the fix! I did a quick check with 1.7.9.0, and it seems to work fine now.
