### ISSUE TITLE
Request window when closing changed text

### ISSUE THREAD

**Issue by adoeller** [Alexey-T/CudaLister#97]
ATM it is asking "File was modified. Save it?" "YES|Cancel"

Cancel means to cancel the leaving of the window, i.e. going back to the text.
The buttons should read "YES|NO", as it is not possible to go back to the text.

**Comment by ildarkhasanshin** [comment]
ct
![image](https://user-images.githubusercontent.com/8765305/200320212-5bd14f67-3675-4b06-a9e7-298979e55152.png)
maybe: [Don't Save] [Cancel] [Save]

vscode
![image](https://user-images.githubusercontent.com/8765305/200319973-d166362e-4138-4f24-a841-2cefcdc57ebe.png)

st4
![image](https://user-images.githubusercontent.com/8765305/200320026-da0699c6-367c-404d-89fd-f1ccb941b7b5.png)

**Comment by adoeller** [comment]
i was talking about the lister
![grafik](https://user-images.githubusercontent.com/45470571/200324673-dfb72993-add0-41ef-8049-072903306b59.png)

**Comment by ildarkhasanshin** [comment]
oh, didn't notice
then, yes, it suggests three buttons

**Comment by adoeller** [comment]
![grafik](https://user-images.githubusercontent.com/45470571/215345579-4c185d67-98a9-4337-a028-263ab4a4a033.png)

Now there is a third button, thanks.
but when clicking it, it closes the window without saving it anyway.

**Comment by Alexey-T** [comment]
@springsunx can you fix the issue, pls?

**Comment by Alexey-T** [comment]
so it cannot be solved yet. sorry.
